# Author's infomation
title: Chuan's Blog
author: Chuan Qin
location: "Washington State University"
about: I'm a power system researcher and a Python software programmer. 
description: My personal stack problems and solutions
portfolio_image: "portfolio.JPG"

baseurl: "" # the subpath of your site, e.g. /blog
url: "chuanqin1230.github.io" # the base hostname & protocol for your site, e.g. http://example.com


enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-instagram
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/"
     
share:
  twitter_username: github.io
  fb_appid: 1749788565247320
  
urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
#Plugins
plugins:
  - jekyll-paginate
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
theme: jekyll-theme-cayman